# Generated by Django 5.0.4 on 2024-04-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='videoinfo',
            name='aweme_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
